template: 'templates/client_template.py.mako'
clientType: mujinvision
templateArgs:  # Strings are added to client_template.py.mako
  clientTaskName: binpicking
  parentClassFile: VisionControllerClient
  parentClassName: VisionControllerClient
generatorSettingsComponents:
  timeout:
    default: 3000.0
    description: Time in seconds after which the command is assumed to have failed.
    type: number
    x-nonPayloadParameterOrder: 0  # Used only inside the client, not sent to the server
  ignoredArgsParam:
    ignoredArgs:
      description: These arguments may be passed to the method, but are ignored.
include:
- components.yaml
x-specModifications:
  services:
    # GetPublishedState:
    #   TODO_CONFIRM_BACKEND: ''
    GetPublishedStateService:
      TODO_CONFIRM_BACKEND: ''
      x-omitRegularReturnStatement: true
      parameters:
        timeout:
            paramOrderingIndex: 0
            $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    Ping:
      TODO_CONFIRM_BACKEND: ''
      x-omitRegularReturnStatement: true
      parameters:
        timeout:
            paramOrderingIndex: 0
            $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    SetLogLevel:
      TODO_CONFIRM_BACKEND: ''
      x-omitRegularReturnStatement: true
      parameters:
        componentLevels:
          paramOrderingIndex: 0
        timeout:
          paramOrderingIndex: 1
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    Cancel:
      TODO_CONFIRM_BACKEND: ''
      x-omitRegularReturnStatement: true
      parameters:
        timeout:
          paramOrderingIndex: 0
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    Quit:
      TODO_CONFIRM_BACKEND: ''
      x-omitRegularReturnStatement: true
      parameters:
        timeout:
          paramOrderingIndex: 0
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    GetTaskStateService:
      TODO_CONFIRM_BACKEND: ''
      x-omitRegularReturnStatement: true
      parameters:
        taskId:
          paramOrderingIndex: 0
        cycleIndex:
          paramOrderingIndex: 1
        taskType:
          paramOrderingIndex: 2
        timeout:
          paramOrderingIndex: 3
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    GetVisionStatistics:
      TODO_CONFIRM_BACKEND: ''
      parameters:
        cycleIndex:
          paramOrderingIndex: 1
        taskId:
          paramOrderingIndex: 0
        timeout:
          paramOrderingIndex: 3
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
        taskType:
          paramOrderingIndex: 2
    GetLatestDetectedObjects:
      TODO_CONFIRM_BACKEND: ''
      parameters:
        cycleIndex:
          paramOrderingIndex: 1
        taskId:
          paramOrderingIndex: 0
        timeout:
          paramOrderingIndex: 3
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
        taskType:
          paramOrderingIndex: 2
    GetLatestDetectionResultImages:
      TODO_CONFIRM_BACKEND: ''
      parameters:
        newerthantimestamp:
          paramOrderingIndex: 3
        metadataOnly:
          paramOrderingIndex: 5
        sensorSelectionInfos:
          paramOrderingIndex: 4
        timeout:
          paramOrderingIndex: 6
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
        taskId:
          paramOrderingIndex: 0
        taskType:
          paramOrderingIndex: 2
        cycleIndex:
          paramOrderingIndex: 1
    GetDetectionHistory:
      TODO_CONFIRM_BACKEND: ''
      parameters:
        timestamp:
          paramOrderingIndex: 0
        timeout:
          paramOrderingIndex: 1
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    BackupDetectionLog:
      TODO_CONFIRM_BACKEND: ''
      parameters:
        cycleIndex:
          paramOrderingIndex: 0
          required: true
        sensorTimestamps:
          paramOrderingIndex: 1
        fireandforget:
          paramOrderingIndex: 2
          default: false
          $merge: '#/components/Internal_ExecuteCommandParameters/fireandforget'
        timeout:
          paramOrderingIndex: 3
          default: 2.0
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    StopTask:
      TODO_CONFIRM_BACKEND: ''
      parameters:
        timeout:
          paramOrderingIndex: 7
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
        taskTypes:
          paramOrderingIndex: 2
        waitForStop:
          paramOrderingIndex: 4
        removeTask:
          paramOrderingIndex: 5
        taskId:
          paramOrderingIndex: 0
        taskType:
          paramOrderingIndex: 1
        fireandforget:
          $merge: '#/components/Internal_ExecuteCommandParameters/fireandforget'
          paramOrderingIndex: 6
        cycleIndex:
          paramOrderingIndex: 3
    ResumeTask:
      TODO_CONFIRM_BACKEND: ''
      parameters:
        timeout:
          paramOrderingIndex: 6
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
        taskTypes:
          paramOrderingIndex: 2
        waitForStop:
          paramOrderingIndex: 4
        taskId:
          paramOrderingIndex: 0
        taskType:
          paramOrderingIndex: 1
        fireandforget:
          $merge: '#/components/Internal_ExecuteCommandParameters/fireandforget'
          paramOrderingIndex: 5
        cycleIndex:
          paramOrderingIndex: 3
    StartObjectDetectionTask:
      returns:
        dict:
          required: true
          description: Returns immediately once the call completes
      TODO_CONFIRM_BACKEND: ''
      parameters:
        systemState:
          paramOrderingIndex: 0
        timeout:
          paramOrderingIndex: 1
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    StartContainerDetectionTask:
      returns:
        dict:
          required: true
          description: Returns immediately once the call completes
      TODO_CONFIRM_BACKEND: ''
      parameters:
        systemState:
          paramOrderingIndex: 0
        timeout:
          paramOrderingIndex: 1
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'
    StartVisualizePointCloudTask:
      returns:
        dict:
          required: true
          description: Returns immediately once the call completes
      TODO_CONFIRM_BACKEND: ''
      parameters:
        systemState:
          paramOrderingIndex: 0
        timeout:
          paramOrderingIndex: 1
          $merge: '#/components/Internal_ExecuteCommandParameters/timeout'